{% set name = "google-apitools" %}
{% set version = "0.5.32" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c3763e52289f61e21c41d5531e20fbda9cc8484a088b8686fd460770db8bad13

build:
  number: 1
  noarch: python
  entry_points:
    - gen_client = apitools.gen.gen_client:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - fasteners >=0.14
    - httplib2 >=0.8
    - oauth2client >=1.4.12
    - python >={{ python_min }}
    - six >=1.12.0

test:
  imports:
    - apitools
  commands:
    - pip check
    - gen_client --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/google-apitools/
  summary: client libraries for humans
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
